site_name: aimz
site_url: https://markean.github.io/aimz/
site_author: Eunseop Kim

repo_name: markean/aimz
repo_url: https://github.com/markean/aimz

watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, docs]

copyright: Copyright &copy; Eli Lilly and Company

theme:
  name: material
  features:
    - announce.dismiss
    - content.code.copy
    - content.action.view
    - header.autohide
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - search.suggest
    - search.share
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          show_bases: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          docstring_options:
            ignore_init_summary: true
          members_order: source
          line_length: 88
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/markean/aimz
    - icon: fontawesome/solid/paper-plane
      link: mailto:markean@pm.me
  generator: false

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
  - Examples:
    - WIP: wip.md
  - API Reference:
    - Model:
      - ImpactModel: impact_model.md
    - Utils:
      - Data:
        - ArrayDataset: array_dataset.md
        - ArrayLoader: array_loader.md
  - Changelog: changelog.md
