name: Ruff

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: ruff-action
        uses: astral-sh/ruff-action@v3
